/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package em.domain.validation;


/**
 * A sample validator interface for {@link em.domain.XClazz}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XClazzValidator {
	boolean validate();

	boolean validateAbstract(boolean value);
	boolean validateDefaultDomainKey(String value);
	boolean validateImplementSerializable(boolean value);
	boolean validateImports(String value);
	boolean validateIsPersistent(boolean value);
	boolean validateMethods(String value);
	boolean validateMethodVisibility(boolean value);
	boolean validateName(String value);
	boolean validatePackageName(String value);
	boolean validatePrimaryKey(String value);
	boolean validateSerializable(boolean value);
	boolean validateSubImports(String value);
	boolean validateSuperClassName(String value);
	boolean validateSuperClassPackage(String value);
}
